services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server-backend: &server-backend
    image: ruby
    container_name: server-backend
    ports:
      - 3001:3001
    volumes:
      - bundle:/usr/local/bundle
      - ./backend:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "bundle install && ruby server.rb -s puma -p 3001 -o '0.0.0.0'"

  redis:
    image: redis
    container_name: redis

  sidekiq:
    <<: *server-backend
    container_name: sidekiq
    ports: []
    command: bash -c "bundle install && sidekiq -r ./app/jobs/import_tests_job.rb"

  server-frontend: &server-frontend
    image: ruby
    container_name: server-frontend
    ports:
      - 3000:3000
    volumes:
      - bundle:/usr/local/bundle
      - ./frontend:/app
    working_dir: /app
    command: bash -c "bundle install && ruby server.rb -s puma -p 3000 -o '0.0.0.0'"

volumes:
  database:
  bundle: