services:
  database: &database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: postgres

  server:
    image: ruby
    ports:
      - 3000:3000
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app
    command: bash -c "bundle install && ruby server.rb -s puma -p 3000 -o '0.0.0.0'"

  populate_database:
    image: ruby
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app/utils
    command: bash -c "bundle install && ruby import_from_csv_to_db.rb"
    depends_on:
      - database

  test_database:
    <<: *database
    volumes:
      - test_pgdata:/var/lib/postgresql/data

  tests:
    image: ruby
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app/spec
    command: bash -c "bundle install && rspec *"
    depends_on:
      - test_database

volumes:
  pgdata:
  test_pgdata:
  bundle: