services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - network
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: postgres

  prepare_database:
    image: ruby
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app/bin
    command: bash -c "bundle install && ruby import_from_csv_to_db.rb"
    networks:
      - network
    depends_on:
      - database

  server:
    image: ruby
    ports:
      - 3000:3000
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app
    command: bash -c "bundle install && ruby server.rb"
    networks:
      - network

  tests:
    image: ruby
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app/spec
    command: bash -c "bundle install && rspec *"

volumes:
  pgdata:
  bundle:

networks:
  network: