services:
  database: &database
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server: &server
    image: ruby
    container_name: server
    ports:
      - 3001:3001
    volumes:
      - bundle:/usr/local/bundle
      - ./backend:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "bundle install && ruby server.rb -s puma -p 3001 -o '0.0.0.0'"

  redis:
    image: redis

  sidekiq:
    <<: *server
    container_name: sidekiq
    ports: []
    command: bash -c "bundle install && sidekiq -r ./app/jobs/import_tests_job.rb"

volumes:
  database:
  bundle: